const data = [
  {
    qty: 0,
    name: "Ardor Aviator",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Ray-Ban",
    category: "Sports",
    gender: "Men",
    weight: "200g",
    quantity: 10,
    image: "/img/sun3.png",
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
    trending: true,
  },
  {
    qty: 0,
    name: "Caper Active",
    description:
      "Pellentesque ac tortor sed ipsum feugiat condimentum. Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Persol",
    category: "Sports",
    gender: "Men",
    weight: "100g",
    quantity: 5,
    image: "/img/sun4.png",
    rating: 4.8,
    price: 1299,
    newPrice: 1199,
    trending: true,
  },
  {
    qty: 0,
    name: "Alder Street",
    description:
      "Integer et nunc in turpis maximus facilisis ac ac elit. Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Kate Spade",
    category: "Sports",
    gender: "Unisex",
    weight: "750g",
    quantity: 15,
    image: "/img/sun5.png",
    rating: 4.7,
    price: 2999,
    newPrice: 2000,
    trending: true,
  },
  {
    qty: 0,
    name: "Corral Round",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna. Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Carrera",
    category: "Sports",
    gender: "Unisex",
    weight: "300g",
    quantity: 8,
    image: "/img/sun7.png",
    rating: 3.8,
    price: 2499,
    newPrice: 2300,
  },
  {
    qty: 0,
    name: "Hyperclax Active",
    description:
      "Aenean at velit consequat, faucibus mi id, tempor velit. Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Oakley",
    category: "Sports",
    gender: "Women",
    weight: "900g",
    quantity: 3,
    image: "/img/sun8.png",
    rating: 3.5,
    price: 3999,
    newPrice: 3500,
  },
  {
    qty: 0,
    name: "Rose Gold Chase",
    description:
      "Vivamus mattis quam sed libero pretium ullamcorper. Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Ray-Ban",
    category: "Vision",
    gender: "Women",
    weight: "120g",
    quantity: 9,
    image: "/img/sun9.png",
    rating: 4.3,
    price: 2999,
    newPrice: 2599,
  },
  {
    qty: 0,
    name: "Full Rim Airflex",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: "/img/sun10.png",
    rating: 4.8,
    price: 4999,
    newPrice: 3999,
  },
  {
    qty: 0,
    name: "Mercury Rounded Red",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 7,
    image: "/img/sun11.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4300,
  },
  {
    qty: 0,
    name: "Candyfloss-302",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Ray-Ban",
    category: "Sunglasses",
    gender: "Men",
    weight: "200g",
    quantity: 10,
    image: "/img/sun3.png",
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
  },
  {
    qty: 0,
    name: "Phenomenal Mercury-02",
    description:
      "Pellentesque ac tortor sed ipsum feugiat condimentum. Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Persol",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "100g",
    quantity: 5,
    image: "/img/sun4",
    rating: 4.6,
    price: 2000,
    newPrice: 1600,
  },
];

module.exports = data;
